### ISSUE TITLE
Python bindings issues

### ISSUE THREAD

**Issue by 3nids** [qgis/QGIS-Mac-Packager#54] opened 2020-07-02 11:55 UTC
* [ ] pyqt-webkit is missing ([formula](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/osgeo-pyqt-webkit.rb))
* [x] PyQt5 modules linking to Qt see #52

**Comment by PeterPetrik** [comment] 2020-08-10 12:26
duplicate of #65

**Closed by PeterPetrik** 2020-08-10 12:26 UTC
Labels: qgis-deps
