### ISSUE TITLE
GeoPDF Export fails

### ISSUE THREAD

**Issue by thayeray** [qgis/QGIS-Mac-Packager#75] opened 2020-08-21 18:43 UTC
Export of GeoPDF fails with the following error: "could not create a print device". The export dialog is now working, but the process fails.

**Comment by PeterPetrik** [comment] 2020-08-24 04:50
maybe duplicate of 
- https://github.com/qgis/QGIS/issues/38064
- https://github.com/qgis/QGIS/issues/34438

Can you create any geopdf export (e.g. simple vector layer) or even the simplest fails?

**Comment by thayeray** [comment] 2020-08-24 12:53
In theory it could be qgis/QGIS#38064 since I can not add even the simplest layer (4269, or 4326) to a new project and have it automatically assign a CRS to layers that are correctly assigned in build1 (3.10.8 LTR).But even after I manually assign both the layer and project CRS it still says "Could not create print device." when trying to export a geopdf.So it probably is not qgis/QGIS#38064.

    On Monday, August 24, 2020, 12:51:07 AM EDT, Peter Petrik <notifications@github.com> wrote:  
 
 


maybe duplicate of
   
   - qgis/QGIS#38064
   - qgis/QGIS#34438

Can you create any geopdf export (e.g. simple vector layer) or even the simplest fails?

**Comment by PeterPetrik** [comment] 2020-09-04 15:50
fixed in qgis-deps-0.5.4 (i hope)

**Comment by PeterPetrik** [comment] 2020-09-08 07:04
reopening, still an issue "I do still get an error, "Could not create print device" when I try to print Geospatial PDF from the composer"

**Comment by PeterPetrik** [comment] 2020-09-23 12:02
works here, can you please retest with https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200923_062253.dmg

![export_geopdf](https://user-images.githubusercontent.com/804608/94009905-6be7b580-fda5-11ea-946c-9a240da1b07b.gif)

**Comment by thayeray** [comment] 2020-09-24 14:34
I can confirm that this version exports simple maps which can be opened as georeferenced rasters. 
    On Wednesday, September 23, 2020, 08:03:06 AM EDT, Peter Petrik <notifications@github.com> wrote:  
 
 


works here, can you please retest with https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200923_062253.dmg

**Closed** 2020-09-24 15:01 UTC
Labels: bug, feedback, qgis-deps
