### ISSUE TITLE
GDAL 3 and geopdf support

### ISSUE THREAD

**Issue by jctull** [qgis/QGIS-Mac-Packager#26] opened 2019-11-12 18:24 UTC
Current nightly builds agains GDAL 2.x, so we are missing a bunch of great features in QGIS 3.10 with geopdf export options. The Mac packager desperately needs gdal 3 support. As it currently stands, the only way to get georeferenced images out of the composer is to export tiff files to my knowledge.

**Comment by PeterPetrik** [comment] 2019-11-21 10:24
duplicate of #12

**Closed by PeterPetrik** 2019-11-21 10:24 UTC
Labels: duplicate
