### ISSUE TITLE
Support for LERC compression (libtiff >= 4.3 and GDAL >= 3.3)

### ISSUE THREAD

**Issue by avalentino** [qgis/QGIS-Mac-Packager#135] opened 2021-06-23 15:22 UTC
I'm interested in using GeoTIFF data that have been generated using the LERC compression.
It seems that the lates QGIS version 3.20.0 (binary installer for Mac OSX) does not support this feature.

AFAIK the LERC compression requires libtiff >= 4.3 and GDAL >= 3.3, so I assume that it is not a QGIS limitation but just a matter of packaging.

What are plans to update libtiff/GDAL and support LERC compressed GeoTIFF data?

**Comment by PeterPetrik** [comment] 2021-06-24 07:35
Hi, it would require the new qgis-deps package with the library updates.  We will most likely update the stuff for QGIS 3.22, but if you require this sooner for your project drop me a mail on Peter.petrik@lutraconsulting.co.uk

**Comment by andreasneumann** [comment] 2021-06-24 07:39
I agree that LERC is a quite useful GTIFF compression scheme. I also plan to use it more in the future. It would be great if 3.22 could ship with the newer gdal and libtiff that supports LERC.

Another quite important dependency would be GEOS 3.9 or higher, which brings a lot of perfomance and stability optimizations.

**Comment by PeterPetrik** [comment] 2021-06-24 07:44
geos is already at 3.9.1

**Comment by avalentino** [comment] 2021-06-24 07:53
> Hi, it would require the new qgis-deps package with the library updates. We will most likely update the stuff for QGIS 3.22

Thanks @PeterPetrik this is a very good news. According to the [QGIS Roadmap](https://qgis.org/en/site/getinvolved/development/roadmap.html?highlight=release) 3.22 should be in October 2021 (cc @ClementAlbinet).

I assume that for QGIS 3.22 the same updates will made also for other binary installers (windows, linux, etc).
Is it correct?

**Comment by andreasneumann** [comment] 2021-06-24 07:58
> I assume that for QGIS 3.22 the same updates will made also for other binary installers (windows, linux, etc).
> Is it correct?

The different OS are not in sync regarding the dependencies. As long as we don't ship snap versions, we cannot control the availiability of libraries in the different Linux distributions.

Also, the OSGeo4W and standalone/MSI windows installers follow their own separate paths.

From time to time QGIS is definining "minimum" required library versions though, albeit very conservative ... (mostly because of old Linux distributions).

**Comment by hobu** [comment] 2021-09-02 19:45
Chiming in to 👍 LERC support in builds and let people know that they can get LERC support if they use @conda-forge -based QGIS builds right now if they need it.

**Comment by avalentino** [comment] 2021-09-03 05:50
Thanks @hobu, I was not aware of the @conda-forge -based QGIS builds.

**Comment by PeterPetrik** [comment] 2021-09-16 10:02
fixed in https://github.com/qgis/QGIS-Mac-Packager/commit/5e44673145dab5b8eca1d672efe8363b4e0158ff

**Comment by PeterPetrik** [comment] 2021-09-17 05:28
fixed on nightlies, https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20210916_124111.dmg if anyone would like to test?

**Closed by PeterPetrik** 2021-09-17 05:28 UTC
Labels: enhancement, qgis-deps

**Comment by hobu** [comment] 2021-09-17 11:33
Confirmed to be working great with https://hobu-lidar.s3.amazonaws.com/iowa/IA_SouthCentral_1_2020-dsm-1m-LERC.tif  👍 🎊
