### ISSUE TITLE
Missing qgis_mapserver in QGIS 3.12

### ISSUE THREAD

**Issue by rbochet** [qgis/QGIS-Mac-Packager#46] opened 2020-04-26 13:28 UTC
I installed the last version for OSX, but looks like there's no qgis_mapserver. 

I looked in the bin/ dir, but without success, and find cant find it

**Comment by PeterPetrik** [comment] 2020-08-14 07:08
duplicate of #16

**Comment by PeterPetrik** [comment] 2020-09-23 09:16
implemented in https://github.com/qgis/QGIS-Mac-Packager/commit/1a6ccb6e60adbfbbe05839e0c507e675a71c2491

**Comment by PeterPetrik** [comment] 2020-09-23 09:16
![Uploading Screenshot 2020-09-23 at 11.03.17.png…]()

**Closed** 2020-09-29 16:23 UTC
Labels: enhancement
