### ISSUE TITLE
GRASS init error in 3.18.0

### ISSUE THREAD

**Issue by dkav** [qgis/QGIS-Mac-Packager#120] opened 2021-03-01 18:44 UTC
FYI - When you enable the GRASS plugin.

2021-03-01T10:18:09     WARNING    GRASS init error : Problem in GRASS initialization, GRASS provider and plugin will not work : Module built against version 2021-02-10T17:13:06+00:00 but trying to use version 2021-02-10T17:08:53+00:00. You need to rebuild GRASS GIS or untangle multiple installations.

**Comment by PeterPetrik** [comment] 2021-03-02 07:25
duplicate of https://github.com/qgis/QGIS/issues/41782

**Comment by gioman** [comment] 2021-03-02 10:55
@PeterPetrik do you want to keep this open or closing as duplicate?

**Closed** 2021-09-27 12:57 UTC
Labels: bug
